# -*- coding: utf-8 -*-
"""Actividad Práctica Integradora v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UXVPm51i8WY9aOFVo1iRRJVed99kRhGK
"""

# 1. Instalar Java y dependencias de Python
!apt-get update -qq > /dev/null
!apt-get install -y default-jdk -qq > /dev/null
!pip install -q pyspark pykka numpy findspark

import os
import subprocess

# 2. Detectar dinámicamente la ruta REAL de JAVA_HOME en Colab
try:
    java_bin = subprocess.check_output(["which", "java"]).decode("utf-8").strip()
    real_java_path = os.path.dirname(os.path.dirname(os.path.realpath(java_bin)))
    os.environ["JAVA_HOME"] = real_java_path
except Exception:
    os.environ["JAVA_HOME"] = "/usr/lib/jvm/default-java"

os.environ["PATH"] = os.environ["JAVA_HOME"] + "/bin:" + os.environ.get("PATH", "")
os.environ["PYSPARK_PYTHON"] = "/usr/bin/python3"
os.environ["PYSPARK_DRIVER_PYTHON"] = "/usr/bin/python3"

import findspark
findspark.init()

print("--- Verificación del Entorno ---")
print(f"Ruta de JAVA_HOME detectada: {os.environ['JAVA_HOME']}")
!java -version
!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
# %%writefile gpu_process.cu
# #include <iostream>
# #include <vector>
# #include <cuda_runtime.h>
# #include <omp.h>
# 
# // Kernel CUDA para Normalización Min-Max
# __global__ void normalizeKernel(float* d_array, float minVal, float maxVal, int n) {
#     int idx = blockIdx.x * blockDim.x + threadIdx.x;
#     if (idx < n) {
#         if (maxVal > minVal) {
#             d_array[idx] = (d_array[idx] - minVal) / (maxVal - minVal);
#         } else {
#             d_array[idx] = 0.0f;
#         }
#     }
# }
# 
# extern "C" {
#     void process_array(float* h_array, int n, float minVal, float maxVal) {
#         float *d_array;
#         size_t bytes = n * sizeof(float);
# 
#         cudaMalloc(&d_array, bytes);
#         cudaMemcpy(d_array, h_array, bytes, cudaMemcpyHostToDevice);
# 
#         int threadsPerBlock = 256;
#         int blocksPerGrid = (n + threadsPerBlock - 1) / threadsPerBlock;
# 
#         normalizeKernel<<<blocksPerGrid, threadsPerBlock>>>(d_array, minVal, maxVal, n);
# 
#         cudaMemcpy(h_array, d_array, bytes, cudaMemcpyDeviceToHost);
#         cudaFree(d_array);
#     }
# }

import os

os.environ["PATH"] += ":/usr/local/cuda/bin"
os.environ["LD_LIBRARY_PATH"] = os.environ.get("LD_LIBRARY_PATH", "") + ":/usr/local/cuda/lib64"

print("Compilando el kernel CUDA/OpenMP...")
get_ipython().system("nvcc -Xcompiler -fPIC -shared -Xcompiler -fopenmp -o libgpu.so gpu_process.cu")

if os.path.exists("./libgpu.so"):
    print("✅ Librería 'libgpu.so' compilada con éxito.")
else:
    print("❌ Error en la compilación. Verifica que la GPU esté activada.")

import ctypes
import numpy as np

gpu_lib = ctypes.CDLL('./libgpu.so')
gpu_lib.process_array.argtypes = [
    ctypes.POINTER(ctypes.c_float),
    ctypes.c_int,
    ctypes.c_float,
    ctypes.c_float
]

def run_gpu_normalization(data_array):
    arr = np.array(data_array, dtype=np.float32)
    min_val, max_val = float(arr.min()), float(arr.max())
    n = len(arr)

    ptr = arr.ctypes.data_as(ctypes.POINTER(ctypes.c_float))
    gpu_lib.process_array(ptr, n, min_val, max_val)

    np.savetxt("preprocessed_data.csv", arr, delimiter=",", fmt="%.6f")
    return "preprocessed_data.csv"

print("✅ Wrapper de Python (ctypes) cargado correctamente.")

import pykka
import random
import os
import time
from pyspark.sql import SparkSession
from pyspark import SparkContext

# --- Limpieza preventiva de sesiones previas ---
try:
    SparkContext.getOrCreate().stop()
except Exception:
    pass

# --- Inicialización de Spark Context en el Hilo Principal ---
print("Iniciando Spark Session...")
spark = SparkSession.builder \
    .appName("ColabSparkHybrid") \
    .master("local[*]") \
    .config("spark.driver.memory", "2g") \
    .config("spark.driver.bindAddress", "127.0.0.1") \
    .config("spark.ui.enabled", "false") \
    .getOrCreate()

print("✅ Spark Context iniciado y activo correctamente.")

# --- 1. ACTOR DE VALIDACIÓN ---
class ValidationActor(pykka.ThreadingActor):
    def validate(self, data):
        if not data or len(data) == 0:
            raise ValueError("El array de entrada está vacío.")
        print(f"[ValidationActor] Datos validados correctamente ({len(data)} elementos).")
        return True

# --- 2. ACTOR GPU SERVERLESS ---
class GPULambdaActor(pykka.ThreadingActor):
    def process_gpu(self, data, retries=3):
        for attempt in range(1, retries + 1):
            try:
                print(f"[GPULambdaActor] Intento {attempt}: Ejecutando Kernel CUDA/OpenMP...")
                if random.random() < 0.1 and attempt == 1:
                    raise ConnectionError("Simulación de fallo de red/Cold-start serverless.")

                output_file = run_gpu_normalization(data)
                print(f"[GPULambdaActor] Normalización exitosa en GPU -> {output_file}")
                return output_file
            except Exception as e:
                print(f"[GPULambdaActor] Error: {e}. Reintentando...")
                if attempt == retries:
                    raise e

# --- 3. ACTOR SPARK ---
class SparkLauncherActor(pykka.ThreadingActor):
    def launch_job(self, input_csv):
        print(f"[SparkLauncherActor] Ejecutando Jobs de Spark sobre {input_csv}...")

        # Reutilizar la sesión activa de Spark
        spark_session = SparkSession.builder.getOrCreate()

        # --- PIPELINE 1: RDD ---
        start_rdd = time.time()
        rdd = spark_session.sparkContext.textFile(input_csv)
        rdd_parsed = rdd.map(lambda line: float(line))
        rdd_sum = rdd_parsed.reduce(lambda a, b: a + b)
        rdd_count = rdd_parsed.count()
        rdd_mean = rdd_sum / rdd_count
        time_rdd = time.time() - start_rdd

        # --- PIPELINE 2: DATAFRAME ---
        start_df = time.time()
        df = spark_session.read.csv(input_csv, inferSchema=True).toDF("val")
        df_result = df.groupBy().avg("val").collect()
        df_mean = df_result[0][0]
        time_df = time.time() - start_df

        speedup = time_rdd / time_df if time_df > 0 else 0.0

        return {
            "rdd_time_sec": round(time_rdd, 4),
            "df_time_sec": round(time_df, 4),
            "speedup": round(speedup, 2),
            "rdd_mean": float(rdd_mean),
            "df_mean": float(df_mean)
        }

# --- 4. ACTOR ORQUESTADOR PRINCIPAL ---
class JobManagerActor(pykka.ThreadingActor):
    def __init__(self):
        super().__init__()
        self.validator = ValidationActor.start()
        self.gpu_actor = GPULambdaActor.start()
        self.spark_actor = SparkLauncherActor.start()

    def execute_pipeline(self, raw_data):
        self.validator.proxy().validate(raw_data).get()
        csv_file = self.gpu_actor.proxy().process_gpu(raw_data).get()
        spark_metrics = self.spark_actor.proxy().launch_job(csv_file).get()

        return {
            "status": "SUCCESS",
            "processed_elements": len(raw_data),
            "metrics": spark_metrics
        }

    def on_stop(self):
        self.validator.stop()
        self.gpu_actor.stop()
        self.spark_actor.stop()

print("✅ Sistema de Actores Pykka configurado y listo.")

import json
import numpy as np

# 1. Generar dataset aleatorio de prueba (1,000,000 elementos)
print("Generando dataset aleatorio de prueba (1,000,000 elementos)...")
dataset = np.random.uniform(low=10.0, high=500.0, size=1000000).tolist()

# 2. Iniciar el Actor Orquestador
orchestrator = JobManagerActor.start()

print("\n--- INICIANDO PIPELINE HÍBRIDO SERVERLESS ---")
try:
    # 3. Lanzar la ejecución completa del flujo
    future = orchestrator.proxy().execute_pipeline(dataset)
    results = future.get()

    # 4. Mostrar respuesta consolidada en formato JSON
    print("\n--- RESULTADO FINAL CONSOLIDADO ---")
    print(json.dumps(results, indent=4))

finally:
    orchestrator.stop()